[versions]
agp = "8.9.0"
appcompat = "1.6.1"
material = "1.10.0"
commonsLang3 = "3.7"
fastjson = "1.2.78"

[libraries]
appcompat = { group = "androidx.appcompat", name = "appcompat", version.ref = "appcompat" }
material = { group = "com.google.android.material", name = "material", version.ref = "material" }
commons-lang3 = { module = "org.apache.commons:commons-lang3", version.ref = "commonsLang3" }
fastjson = { module = "com.alibaba:fastjson", version.ref = "fastjson" }

[plugins]
android-application = { id = "com.android.application", version.ref = "agp" }

